##  ################################
#   Set up tc offload for Mellanox #
##  ################################

- name: Enable tc offload for {{ dut_interface_1 }}
  shell: ethtool -K {{ dut_interface_1 }} hw-tc-offload on
- name: Create vf
  shell: echo 1 > /sys/class/net/{{ dut_interface_1 }}/device/sriov_numvfs

- name: Get driver for pf
  shell: ethtool -i {{ dut_interface_1 }} | grep driver | awk '{print $2}'
  register: dut_nic1_driver

- name: Get pci id for vf
  shell: ls -l /sys/bus/pci/devices/{{ dut_interface_1_pciid }}/virtfn0 | sed 's/.*\///'
  register: vf_pciiid

- name: Unbind vf from kernel
  shell: echo {{ vf_pciiid.stdout }} > /sys/bus/pci/drivers/{{ dut_nic1_driver.stdout }}/unbind
- name: Change the e-switch mode from legacy
  shell: devlink dev eswitch set pci/{{ dut_interface_1_pciid }} mode switchdev
- name: Bind vf to kernel
  shell: echo {{ vf_pciiid.stdout }} > /sys/bus/pci/drivers/{{ dut_nic1_driver.stdout }}/bind
- name: Get vf name again after change mode to eswitch
  shell: ls /sys/bus/pci/devices/{{ vf_pciiid.stdout }}/net
  register: vf_name

# Get VF representor
- name: Get PF rep
  shell: ls /sys/bus/pci/devices/{{ dut_interface_1_pciid }}/net
  register: pf_rep
- name: Get PF phys_port_name
  shell: cat /sys/class/net/{{ pf_rep.stdout }}/phys_port_name | sed 's/p//'
  register: pf
- name: Get ifaces list
  shell: ls /sys/class/net/
  register: if_list
- name: Get VF rep
  shell: cat /sys/class/net/{{ item }}/phys_port_name | grep "pf{{pf.stdout}}vf0" &>/dev/null && echo "{{item}}" > /tmp/vf_rep.txt
  ignore_errors: yes
  with_items: "{{if_list.stdout_lines}}"
- name: save VF rep to vf_rep
  shell: cat /tmp/vf_rep.txt
  register: vf_rep
