- name: T-Rex Setup 
  hosts: trex
  vars:
    ovs_perf_url: https://github.com/chaudron/ovs_perf.git
    ovs_perf_dir: /root/ovs_perf
    xena_lib_url: https://github.com/fleitner/XenaPythonLib
    xena_lib_dir: /root/XenaPythonLib
  vars_files:
    - ./test_settings.yml
  tasks:

    # Install repositories on T-Rex server #
    - name: Install required packages for T-Rex server and tuned
      dnf:
        name:
          - bc
          - emacs
          - gcc
          - git
          - lshw
          - pciutils
          - python3-devel
          - python3-pip
          - python3-setuptools
          - tmux
          - tuned-profiles-cpu-partitioning
          - tar
          - wget
          - net-tools

    # Install EPEL repositories
    - name: Install EPEL repositories
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install packages from EPEL repo
      dnf:
        name:
          - zeromq-devel
          - sshpass
        state: present

    - name: Remove EPEL repo to avoid conflict
      dnf:
        name: epel-release-7
        state: absent

    # Python settings
    - name: Link /usr/bin/python to /usr/bin/python3
      file:
        src: "/usr/bin/python3"
        dest: "/usr/bin/python"
        state: link
    - name: Link pip to pip3
      file:
        src: "/usr/bin/pip3"
        dest: "/usr/bin/pip"
        state: link
    - name: Install required python modules
      pip:
        name:
          - enum34
          - natsort
          - netaddr
          - matplotlib
          - scapy
          - spur
          - pyyml
          - wheel

    # Install PVP test script
    - name: git clone "{{ ovs_perf_url }}"
      git:
        repo: "{{ ovs_perf_url }}"
        clone: yes
        dest: "{{ ovs_perf_dir }}"
    - name: git clone "{{ xena_lib_url }}"
      git:
        repo: "{{ xena_lib_url }}"
        clone: yes
        dest: "{{ xena_lib_dir }}"
    - name: Install xena libraries
      shell: python setup.py install
      args:
        chdir: "{{ xena_lib_dir }}"

    # Install T-Rex
    - name: Download T-Rex
      shell:
        cmd: >
          mkdir -p "{{ trex_dir }}" &&
          mkdir -p "{{ trex_dir }}/trex" &&
          pushd /root/trex &&
          [[ -f $(basename "{{ trex_url }}") ]] || wget -nv -N "{{ trex_url }}" &&
          tar xzf $(basename "{{ trex_url }}") --strip 1 -C trex/ &&
          pushd trex &&
          tar -C "{{ ovs_perf_dir }}" --strip 2 -xzf trex_client_*.tar.gz trex_client/interactive/trex &&
          tar -C "{{ ovs_perf_dir }}/trex" --strip 1 -xzf trex_client_*.tar.gz trex_client/external_libs &&
          python dpdk_setup_ports.py -c {{trex_interface_1}} {{trex_interface_2}} --force-mac -o /etc/trex_cfg.yaml &&
          popd &&
          popd

    # Setting bootargs for iommu and hugepages
    - name: Checking iommu settings
      shell:
        cmd: >
          grep intel_iommu=on /proc/cmdline &&
          grep iommu=pt /proc/cmdline
      failed_when: false
      ignore_errors: yes
      register: iommu_ok
    - name: Checking hugepage settings
      shell:
        cmd: >
          grep hugepages=32 /proc/cmdline &&
          grep hugepagesz=1G /proc/cmdline &&
          grep default_hugepagesz=1G /proc/cmdline &&
          grep iommu=pt /proc/cmdline &&
          grep intel_iommu=on /proc/cmdline
      failed_when: false
      ignore_errors: yes
      register: hugepage_ok
    - name: Setting bootargs
      shell: "grubby --args='intel_iommu=on iommu=pt default_hugepagesz=1G hugepagesz=1G hugepages=32' --update-kernel=$(grubby --default-kernel)"
      when: iommu_ok.rc != 0 or hugepage_ok.rc != 0

    # Setting isolated CPUs and tune to cpu-partitioning
    - name: Getting isolated core list
      shell: cat /etc/trex_cfg.yaml | grep threads | awk '{ print $2 }' | tr -d "[]"
      register: corelist
    - name: Checking isolated cpus
      shell:
        cmd: >
          grep "nohz_full={{ corelist.stdout }}" /proc/cmdline &&
          grep "rcu_nocbs={{ corelist.stdout }}" /proc/cmdline
      failed_when: false
      ignore_errors: yes
      register: tuned_ok
    - name: Set tuned
      shell: >
        sed -i '/^isolated_cores=/d' /etc/tuned/cpu-partitioning-variables.conf &&
        echo "isolated_cores={{corelist.stdout}}" >> /etc/tuned/cpu-partitioning-variables.conf &&
        tuned-adm profile cpu-partitioning
    - name: Stop irqbalance service
      systemd:
        name: irqbalance
        state: stopped
    - name: Restart tuned service
      systemd:
        name: tuned
        state: restarted
        daemon_reload: yes

    # reboot system if need
    - name: reboot T-Rex server if need
      reboot:
      when: >
        iommu_ok.rc != 0 or
        hugepage_ok.rc != 0 or
        tuned_ok.rc != 0

    # Create pvp results folder
    - name: Create pvp results folder
      shell: mkdir -p ~/pvp_results
